### ISSUE TITLE
Anglar webpage generator doesn't work

### ISSUE THREAD

**Issue by kOstovic** [hyperledger/composer#3868]
## Context

I follow a tutorial(link under) and it seems someone pushed code for generation of "concept" but it didnt created concept generator, with commented code as suggested bellow everything works
## Expected Behavior

Whole angular page should generate
## Actual Behavior

Error, cant copy 
src/app/concept/*
cause it doesnt exist
## Possible Fix

comment code from line 823 to 860
of composer/packages/generator-hyperledger-composer/generators/angular/index.js
until generator for concept is created in 
composer/packages/generator-hyperledger-composer/generators/angular/templates/src/app/concept
## Steps to Reproduce
try to create angular app from this tutorial
https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html
step 6
yo hyperledger-composer:angular

## Your Environment

* Version used:
0.19.1 version of composer
node 8.9.1

**Comment by sstone1** [comment]
@EllisHenderson @KaiUsher please look at this, sounds like the generator fails to work with business networks that contain concepts.

**Comment by nekyl** [comment]
Concept can't properly represented in angular app: for example i have concept, named position:
``concept Position {
String long
String lang
}
But what i see on angular is just this one: [https://imgur.com/a/p7SB6gJ](url)

no matter how many variables are in there, i see just [object Object] 
I think, that should be fixed as soon as possible. it was already in the version 0.16 like this.

**Comment by EllisHenderson** [comment]
Please see issue #3136 for a wider scope on the angular generator. 

A bulk of the current code for concepts is necessary to fix #3196 as without it if your model file contained a concept, the app would fail to compile. 

Whilst an app will now compile if it contains a concept, there is no handling for concepts like this yet and as a result you're still unable to create an asset containing one.

**Comment by EllisHenderson** [comment]
@nekyl I'm unable to view the image you linked, but from the sounds of it you're creating an asset which contains a concept by using the rest server? 

Doing this bypasses the issue to some degree as it allows you to create an asset, but since there isn't any handling for concepts the fields will just appear as '[object Object]'

**Comment by nekyl** [comment]
@EllisHenderson No it's just simple concept belongs to an participant  for example:
participant User {
String id
Position pos
}

concept Position {
Double long
Double lat
}
what i in angular get is here: https://imgur.com/a/oVjJ4g2

**Comment by EllisHenderson** [comment]
Closing this.
Have opened an issue which fully details this problem #3927

**Comment by AmanUllah710** [comment]
anyone got solution using 0.20.0 version
