### ISSUE TITLE
Angular application does not get generated successfully even though the rest web server is generated successfully

### ISSUE THREAD

**Issue by rohankk2** [hyperledger/composer#4120]
I was running through the hyperledger tutorials on the following site:
https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html
Everything Worked fine till i tried to generate the angular application. Also In my RestWebAPI only one transaction shows, however when I run the app on the IBM playground it shows both my transactions. Hence Im confused about why the angular application doesnt work and why the REST Web API only shows one of my transactions.

## Context

The angular application that should run does not

## Expected Behavior

The angular application should successfully generate

## Actual Behavior

The following error occurs : 
ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 35:17 in the original .ts file), resolving symbol AppModule in /Users/rohank2/GraybarBlockchainPOC/fabric-dev-servers/tutorial-network/tutorial-network/src/app/app.module.ts
webpack: Failed to compile.

## Possible Fix

If I make any changes and save them to the ts file (like change a variable name etc) the error doesnt come anymore however, on the localhost server the app is either stuck on loading.... or keeps refreshing for some reason.

## Steps to Reproduce

To Reproduce follow the steps in this tutorial:
https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

Could not find this particular issue in any of the above sites.
## Context

Im trying to set up a private blockchain test network for my enterprise, with my Pc as the host. Other computers on the same wifi network should be able to access the angular app that runs the smart contracts Ive written.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:
Node version 8.11.1 
Composer version 0.19.5

**Comment by ashu8472** [comment]
Had the same issue. try following:

Go to app.module.ts in the created angular application

locate 
Line 27 @NgModule({
Line 28 declarations:[
Line 29 AppComponent,
Line 30 HomeComponent,
Line 31 ,
Line 32 ,
]

Remove comma in line 30 and remove line 31 & 32

it will look like below code after change
Line 27 @NgModule({
Line 28 declarations:[
Line 29 AppComponent,
Line 30 HomeComponent
]

Save it and do npm start again, this should resolve the issue.

**Comment by annumberhocker** [comment]
We tried this and still have the same issue.  A Transactions Menu is created, but when a Transaction is selected, only a description of what is to be entered appears.  Not the ability to Create any of the defined Transaction functions.

**Comment by sameer1709** [comment]
Try to generate angular application by using new rest api instead of selecting existing api..
It will help and resolve your further issue like 404 error....page could not be found.  
Can run your app typing localhost:4200/ in browser .

**Comment by davidkel** [comment]
@rohankk2 Is this still an issue ?

**Comment by davidkel** [comment]
Closing as no further information provided.

**Comment by vanishtachangea** [comment]
I am also getting this issue. 
I am using Vagrant and Virtual Box with Ubuntu 16.04 LTS. 
I am able to load the http://localhost:3000/explorer/ rest api but not the angular app : http://localhost:4200/Pricelist

Does anybody knows how to fix this urgently?

Thanks
